version: '3.8'

services:
  db-mascotas:
    # Usamos la imagen con PostGIS habilitado para la geolocalización futura
    image: postgis/postgis:15-3.3 
    container_name: sanosysalvos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sanosysalvos_mascotas
    ports:
      - "5432:5432" # Expone el puerto de Postgres hacia tu entorno local
    volumes:
      - postgres_mascotas_data:/var/lib/postgresql/data # Asegura que los datos no se borren al apagar el contenedor

volumes:
  postgres_mascotas_data: