# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# El puerto donde la API estará escuchando las peticiones del frontend
server.port=8080
spring.application.name=gestormascotas

# ===============================
# CONEXIÓN A POSTGRESQL (DOCKER)
# ===============================
# URL de conexión: apunta al localhost en el puerto 5432 (expuesto por Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvos_mascotas
# Credenciales (deben coincidir exactamente con las de tu docker-compose.yml)
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Le dice a Hibernate que estamos usando PostgreSQL para que optimice las consultas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 'update' es clave en desarrollo: lee tus clases @Entity y crea/actualiza las tablas en la BD automáticamente
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL reales que Spring Boot ejecuta por debajo (muy útil para encontrar errores)
spring.jpa.show-sql=true